id: load_statistic_canada_to_raw
namespace: stats_canada
description: |
  Loads the latest month of data from GCS into BigQuery raw_data.stats_canada_raw using incremental refresh.

triggers:
  - id: monthly_trigger
    type:  io.kestra.plugin.core.trigger.Schedule
    cron: "15 9 8 * *"  # 9:15 AM UTC on the 8th of every month , this is slightly after the load to gsc bucket has been done from the api call.
  

tasks:
  - id: run_incremental_loader
    type: io.kestra.core.tasks.scripts.Bash
    warningOnStdErr: false
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "{{kv('gcp_credentials_path')}}" #"/home/debbyalenkhe/capstone-project-453407-95a4e7e6884e.json"
    commands:
      - echo " Running incremental loader..."
      - /home/debbyalenkhe/venv/bin/python "{{kv('bigquery_python_script_path')}}" #/home/debbyalenkhe/load_statistic_canada_to_raw.py
